Table Game {
  id integer [pk]
  name string [not null]
  players integer [not null]
  date_release date [not null]
  gender integer [ref: - Gender.id, not null]
}

Table Gender {
  id integer [pk]
  name string [not null]
}

Table Player {
  id integer [pk]
  main integer [ref: - Game.id]
  nick string [not null, unique]
  email string [not null, unique]
  active boolean [not null, default: true]
}

Table TournamentPlayer {
  elo_score integer [not null]
  player integer [ref: > Player.id, pk]
  tournament integer [ref: > Tournament.id, pk]
  registration_date date [not null, default: `now()`]
}

Table Tournament {
  id integer [pk]
  name string [not null]
  end_date date [not null]
  start_date date [not null]
  game integer [ref: - Game.id]
  player_limit integer [not null]
  owner integer [ref: - Player.id]
  status integer [ref: - TournamentStatus.id]
}

Table TournamentStatus {
  id integer [pk]
  name string [not null]
}

Table Match {
  id integer [pk]
  match_time date [not null]
  round_number integer [not null]
  duration_minutes integer [not null]
  status integer [ref: - MatchStatus.id]
  tournament integer [ref: > Tournament.id]
}

Table MatchPlayer {
  is_winner boolean [not null]
  elo_change integer [not null]
  match integer [ref: - Match.id, pk]
  player integer [ref: - Player.id, pk]
}

Table MatchStatus {
  id integer [pk]
  name string [not null]
}