version: '3'

services:
  vandal-db:
    image: postgres:14
    container_name: vandal-db
    ports:
      - "5432:5432"
    volumes:
      - vandal-data:/var/lin/postgres/data
    environment:
      - POSTGRES_DB=vandal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123

volumes:
  vandal-data: